export default function SideContent() {
  return (
    <aside className="flex flex-none flex-col gap-[16px] w-[452px] rounded-[20px] shadow-md">
      <div className="flex flex-col gap-[8px] bg-[#C8FF00] rounded-[20px] px-[16px] py-[12px]">
        <h4 className="text-[24px] font-semibold">AI Summary</h4>
        <p className="text-[16px]">
          {`$PAOFU, representing Xiaohongshu's viral cat 'Wang Paofu', with 5 million followers, now a token. No detailed project features or roadmap provided.`}
        </p>
        <div className="flex flex-row gap-[16px] bg-[#EEFFB0] items-center">
          <div className="bg-[#F6F6F6] rounded-[12px] px-[16px] py-[8px]">
            <div className="text-[16px] font-semibold">PeerX</div>
          </div>
          <div className="text-[12px]">Auto generated by PeerX, DYOR.</div>
        </div>
      </div>

      <div className="flex flex-col gap-[8px] rounded-[20px] px-[16px] py-[12px]">
        <h4 className="text-[24px] font-semibold"></h4>
        <div className="flex flex-row gap-[16px]">
          <div className="bg-[#F6F6F6] rounded-[12px] px-[16px] py-[8px]">
            <div className="text-[16px] font-semibold"></div>
          </div>
        </div>
      </div>
    </aside>
  )
}